### ISSUE TITLE
beta2 TODO

### ISSUE THREAD

**Issue by avsm** [realworldocaml/book#2088]
## Release Task List
- [x] move packaging out of book and online @avsm
- [x] move installation out of book and online @avsm
- [x] convert objects+imperative-programming chapters to new tools  @jyh
- [x] get blurb updated @yminsky
